# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374912c255d0d0885d0786ad15941203db313ef7947526aff64a153f896e099a32482cf6c8b90c06b5d0581a7ccb3149cecb3245ac4e1f4c0f8c019aff3b798c

test:
  secret_key_base: d2f1486bf9e3cbe4042b4ebafa71de41bb822855ce43773bbb5d660808c8b8268fdd92a4604dd628a055a4ef71ebbb2fd69999297d7295a2a2f2f6171ebbf743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
